import { Injectable } from "@nestjs/common";
import PDFDocument from "pdfkit";
import { DatabaseService } from "../../common/database.service";

type ExportEntryRow = {
  id: string;
  occurred_at: Date;
  extracted_json: Record<string, unknown> | null;
  red_flags: { category: string; severity: string }[] | null;
};

@Injectable()
export class ExportService {
  constructor(private readonly db: DatabaseService) {}

  async generateDoctorPdf(userId: string, days: number): Promise<Buffer> {
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
    const entries = await this.db.query<ExportEntryRow>(
      `SELECT
         je.id,
         je.occurred_at,
         ae.extracted_json,
         COALESCE(
           jsonb_agg(jsonb_build_object('category', rfe.category, 'severity', rfe.severity))
             FILTER (WHERE rfe.id IS NOT NULL),
           '[]'::jsonb
         ) AS red_flags
       FROM ${this.db.table("journal_entries")} je
       LEFT JOIN ${this.db.table("ai_extractions")} ae ON ae.journal_entry_id = je.id
       LEFT JOIN ${this.db.table("red_flag_events")} rfe ON rfe.journal_entry_id = je.id
       WHERE je.user_id = $1 AND je.occurred_at >= $2
       GROUP BY je.id, je.occurred_at, ae.extracted_json
       ORDER BY je.occurred_at ASC`,
      [userId, since]
    );

    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 48 });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      doc.fontSize(18).text("Women’s Health Journal Companion AI Summary");
      doc.moveDown();
      doc.fontSize(10).text("Generated by AI - informational only. This is not a diagnosis.");
      doc.moveDown();
      doc.fontSize(12).text(`Range: last ${days} days`);
      doc.moveDown();

      for (const entry of entries.rows) {
        doc.fontSize(12).text(entry.occurred_at.toISOString().slice(0, 10), { underline: true });
        doc.fontSize(10).text(JSON.stringify(entry.extracted_json ?? {}, null, 2));
        if (entry.red_flags?.length) {
          doc.text(`Red flags: ${entry.red_flags.map((flag) => `${flag.category} (${flag.severity})`).join(", ")}`);
        }
        doc.moveDown();
      }

      doc.addPage();
      doc.fontSize(14).text("Questions to Discuss");
      doc.fontSize(10).list([
        "Which patterns feel persistent, worsening, or disruptive?",
        "Are cycle, mood, sleep, appetite, pain, or skin changes connected to medications or routine changes?",
        "Which symptoms should be monitored, tested, or evaluated professionally?"
      ]);
      doc.end();
    });
  }
}
