import { Injectable } from "@nestjs/common";
import PDFDocument from "pdfkit";
import { CryptoService } from "../../common/crypto.service";
import { DatabaseService } from "../../common/database.service";

type ExportEntryRow = {
  id: string;
  occurred_at: Date;
  raw_text_ciphertext: string;
  raw_text_nonce: string;
  structured_json: Record<string, unknown>;
  extracted_json: Record<string, unknown> | null;
  red_flags: { category: string; severity: string; guidance: string }[] | null;
};

@Injectable()
export class ExportService {
  constructor(
    private readonly db: DatabaseService,
    private readonly crypto: CryptoService
  ) {}

  async generateDoctorPdf(userId: string, days: number): Promise<Buffer> {
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
    const entries = await this.db.query<ExportEntryRow>(
      `SELECT
         je.id,
         je.occurred_at,
         je.raw_text_ciphertext,
         je.raw_text_nonce,
         je.structured_json,
         ae.extracted_json,
         COALESCE(
           jsonb_agg(jsonb_build_object('category', rfe.category, 'severity', rfe.severity, 'guidance', rfe.guidance))
             FILTER (WHERE rfe.id IS NOT NULL),
           '[]'::jsonb
         ) AS red_flags
       FROM ${this.db.table("journal_entries")} je
       LEFT JOIN ${this.db.table("ai_extractions")} ae ON ae.journal_entry_id = je.id
       LEFT JOIN ${this.db.table("red_flag_events")} rfe ON rfe.journal_entry_id = je.id
       WHERE je.user_id = $1 AND je.occurred_at >= $2
       GROUP BY je.id, je.occurred_at, je.raw_text_ciphertext, je.raw_text_nonce, je.structured_json, ae.extracted_json
       ORDER BY je.occurred_at ASC`,
      [userId, since]
    );

    const reportEntries = entries.rows.map((entry) => ({
      ...entry,
      journalText: this.crypto.decrypt(entry.raw_text_ciphertext, entry.raw_text_nonce)
    }));
    const symptomCounts = countSymptoms(reportEntries);
    const averages = averageMetrics(reportEntries);
    const redFlags = reportEntries.flatMap((entry) =>
      (entry.red_flags ?? []).map((flag) => ({
        ...flag,
        occurredAt: entry.occurred_at
      }))
    );

    return new Promise((resolve) => {
      const doc = new PDFDocument({ margin: 48 });
      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      doc.fontSize(18).text("Women's Health Journal Companion AI Summary");
      doc.moveDown();
      doc.fontSize(10).text("Generated by AI - informational only. This is not a diagnosis.");
      doc.moveDown();
      doc.fontSize(12).text(`Range: last ${days} days`);
      doc.text(`Entries included: ${reportEntries.length}`);
      doc.moveDown();

      doc.fontSize(14).text("Snapshot for Clinician Review");
      doc.fontSize(10).list([
        `Average sleep: ${formatAverage(averages.sleepHours, "hours")}`,
        `Average stress: ${formatAverage(averages.stress, "/10")}`,
        `Average energy: ${formatAverage(averages.energy, "/10")}`,
        `Most frequent logged signals: ${formatCounts(symptomCounts)}`,
        `Red flag events: ${redFlags.length || "none recorded"}`
      ]);
      doc.moveDown();

      doc.fontSize(14).text("Observed Signals");
      const observedSignals = buildObservedSignals(reportEntries);
      doc.fontSize(10).list(observedSignals.length ? observedSignals : ["No repeated AI-extracted signals were available in this range."]);
      doc.moveDown();

      if (redFlags.length) {
        doc.fontSize(14).text("Safety Flags");
        doc.fontSize(10).list(
          redFlags.map(
            (flag) => `${formatDate(flag.occurredAt)}: ${capitalize(String(flag.category))} (${flag.severity}). ${flag.guidance}`
          )
        );
        doc.moveDown();
      }

      doc.fontSize(14).text("Entry Timeline");
      for (const entry of reportEntries) {
        writeEntrySummary(doc, entry);
      }

      doc.fontSize(14).text("Questions to Discuss");
      doc.fontSize(10).list([
        "Which symptoms have persisted, worsened, or disrupted daily life?",
        "Could sleep, stress, cycle timing, appetite, skin changes, pain, or medication changes be connected?",
        "Should any symptoms be monitored, tested, or evaluated professionally?",
        "Are there specific cycle, mood, pain, appetite, or fatigue patterns worth tracking before the next visit?"
      ]);
      doc.moveDown();
      doc.fontSize(8).fillColor("#555555").text(
        "Limitations: This report summarizes user-entered journal data and AI-extracted observations. It may be incomplete or inaccurate and should not replace professional medical judgment."
      );
      doc.end();
    });
  }
}

function writeEntrySummary(doc: PDFKit.PDFDocument, entry: ExportEntryRow & { journalText: string }) {
  const extracted = entry.extracted_json ?? {};
  const structured = entry.structured_json ?? {};
  const symptoms = normalizedSymptoms(extracted);
  const evidence = evidenceQuotes(extracted);
  const metrics = [
    formatMetric("Sleep", structured.sleepHours ?? extracted.sleepHours, "hours"),
    formatMetric("Mood", structured.mood),
    formatMetric("Energy", structured.energy, "/10"),
    formatMetric("Stress", structured.stress, "/10")
  ].filter(Boolean);

  doc.fontSize(11).text(formatDate(entry.occurred_at), { underline: true });
  doc.fontSize(10).text(`Structured metrics: ${metrics.length ? metrics.join("; ") : "not entered"}`);
  doc.text(`AI-observed signals: ${symptoms.length ? symptoms.join(", ") : "none available"}`);
  doc.text(`Confidence: ${formatPercent(extracted.confidence)}`);
  if (evidence.length) {
    doc.text(`Evidence snippets: ${evidence.join(" | ")}`);
  }
  if (entry.red_flags?.length) {
    doc.text(`Safety flags: ${entry.red_flags.map((flag) => `${flag.category} (${flag.severity})`).join(", ")}`);
  }
  doc.text(`Journal note preview: ${truncate(entry.journalText.replace(/\s+/g, " "), 220)}`);
  doc.moveDown();
}

function buildObservedSignals(entries: Array<ExportEntryRow & { journalText: string }>) {
  const counts = countSymptoms(entries);
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .map(([symptom, count]) => `${capitalize(symptom)} appeared in ${count} entr${count === 1 ? "y" : "ies"}.`);
}

function countSymptoms(entries: Array<ExportEntryRow & { journalText: string }>) {
  const counts: Record<string, number> = {};
  for (const entry of entries) {
    for (const symptom of normalizedSymptoms(entry.extracted_json ?? {})) {
      counts[symptom] = (counts[symptom] ?? 0) + 1;
    }
  }
  return counts;
}

function averageMetrics(entries: ExportEntryRow[]) {
  return {
    sleepHours: average(entries.map((entry) => entry.structured_json?.sleepHours ?? entry.extracted_json?.sleepHours)),
    stress: average(entries.map((entry) => entry.structured_json?.stress)),
    energy: average(entries.map((entry) => entry.structured_json?.energy))
  };
}

function normalizedSymptoms(extracted: Record<string, unknown>) {
  const fromList = Array.isArray(extracted.normalizedSymptoms) ? extracted.normalizedSymptoms.map(String) : [];
  const fromFlags = ["fatigue", "acne", "pain", "headache", "digestiveIssues", "libidoChange", "cycleIrregularity"].filter(
    (key) => extracted[key] === true
  );
  return Array.from(new Set([...fromList, ...fromFlags]));
}

function evidenceQuotes(extracted: Record<string, unknown>) {
  if (!Array.isArray(extracted.evidence)) return [];
  return extracted.evidence
    .map((item) => {
      if (!item || typeof item !== "object") return "";
      const quote = (item as { quote?: unknown }).quote;
      return typeof quote === "string" ? `"${truncate(quote.replace(/\s+/g, " "), 120)}"` : "";
    })
    .filter(Boolean)
    .slice(0, 2);
}

function average(values: unknown[]) {
  const numbers = values.map(Number).filter(Number.isFinite);
  if (!numbers.length) return null;
  return numbers.reduce((sum, value) => sum + value, 0) / numbers.length;
}

function formatAverage(value: number | null, suffix: string) {
  return value === null ? "not enough data" : `${value.toFixed(1)} ${suffix}`;
}

function formatCounts(counts: Record<string, number>) {
  const values = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  if (!values.length) return "none available";
  return values
    .slice(0, 5)
    .map(([name, count]) => `${name} (${count})`)
    .join(", ");
}

function formatMetric(label: string, value: unknown, suffix = "") {
  if (value === null || value === undefined || value === "") return "";
  return `${label}: ${value}${suffix}`;
}

function formatPercent(value: unknown) {
  const numberValue = Number(value);
  return Number.isFinite(numberValue) ? `${Math.round(numberValue * 100)}%` : "not available";
}

function formatDate(value: Date) {
  return value.toISOString().slice(0, 10);
}

function truncate(value: string, maxLength: number) {
  return value.length > maxLength ? `${value.slice(0, maxLength - 3)}...` : value;
}

function capitalize(value: string) {
  return value ? `${value[0].toUpperCase()}${value.slice(1)}` : value;
}
