import { Injectable } from "@nestjs/common";
import { ExtractedObservation, JournalCreateInput } from "@whjc/shared";
import { CryptoService } from "../../common/crypto.service";
import { DatabaseService } from "../../common/database.service";
import { AiService } from "../ai/ai.service";
import { PatternService } from "../patterns/patterns.service";
import { SafetyService } from "../safety/safety.service";

type JournalEntryRow = {
  id: string;
  occurred_at: Date;
  raw_text_ciphertext: string;
  raw_text_nonce: string;
  structured_json: Record<string, unknown>;
};

type ExtractionRow = {
  extracted_json: ExtractedObservation;
  analysis_source: string;
  model: string;
};

type RedFlagRow = {
  category: string;
  severity: string;
  guidance: string;
  matched_text: string | null;
  created_at: Date;
};

@Injectable()
export class JournalService {
  constructor(
    private readonly db: DatabaseService,
    private readonly crypto: CryptoService,
    private readonly ai: AiService,
    private readonly patterns: PatternService,
    private readonly safety: SafetyService
  ) {}

  async create(userId: string, input: JournalCreateInput) {
    await this.ensureDemoUser(userId);
    const occurredAt = input.occurredAt ? new Date(input.occurredAt) : new Date();
    const encrypted = this.crypto.encrypt(input.rawText);
    const analysis = input.consentToAiAnalysis
      ? await this.ai.extractJournal(input.rawText, input.structured)
      : null;
    const extraction = analysis?.observation ?? null;

    const entryId = this.db.id();
    const entryResult = await this.db.query<JournalEntryRow>(
      `INSERT INTO ${this.db.table("journal_entries")}
        (id, user_id, occurred_at, raw_text_ciphertext, raw_text_nonce, structured_json)
       VALUES ($1, $2, $3, $4, $5, $6::jsonb)
       RETURNING id, occurred_at, raw_text_ciphertext, raw_text_nonce, structured_json`,
      [entryId, userId, occurredAt, encrypted.ciphertext, encrypted.nonce, JSON.stringify(input.structured ?? {})]
    );
    const entry = entryResult.rows[0];

    if (analysis) {
      await this.db.query(
        `INSERT INTO ${this.db.table("ai_extractions")}
          (id, journal_entry_id, model, analysis_source, extracted_json, confidence)
         VALUES ($1, $2, $3, $4, $5::jsonb, $6)`,
        [this.db.id(), entry.id, analysis.model, analysis.analysisSource, JSON.stringify(analysis.observation), analysis.observation.confidence]
      );
    }

    const redFlags = extraction ? this.safety.evaluate(input.rawText, extraction) : [];
    if (redFlags.length) {
      for (const flag of redFlags) {
        await this.db.query(
          `INSERT INTO ${this.db.table("red_flag_events")}
            (id, user_id, journal_entry_id, category, severity, guidance, matched_text)
           VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [this.db.id(), userId, entry.id, flag.category, flag.severity, flag.guidance, flag.matchedText ?? null]
        );
      }
    }

    return {
      id: entry.id,
      occurredAt: entry.occurred_at,
      extraction,
      analysisSource: analysis?.analysisSource ?? (input.consentToAiAnalysis ? "unknown" : "not_requested"),
      analysisModel: analysis?.model ?? null,
      redFlags,
      disclaimer: "Generated by AI for informational wellness awareness only. This is not a diagnosis."
    };
  }

  async timeline(userId: string, rangeDays: number) {
    const since = new Date(Date.now() - rangeDays * 24 * 60 * 60 * 1000);
    const entries = await this.loadEntries(userId, since);

    const history = entries.map((entry) => ({
      id: entry.id,
      occurredAt: entry.occurredAt.toISOString(),
      structuredJson: entry.structuredJson,
      extraction: entry.extraction
        ? {
            extractedJson: entry.extraction.extractedJson as never,
            analysisSource: entry.extraction.analysisSource,
            model: entry.extraction.model
          }
        : undefined,
      redFlags: entry.redFlags
    }));

    return {
      entries: history,
      patterns: [7, 30, 90].flatMap((window) => this.patterns.detect(history, window)),
      correlations: this.patterns.discoverCorrelations(history)
    };
  }

  async insights(userId: string) {
    const timeline = await this.timeline(userId, 90);
    const insight = await this.ai.generateInsight(timeline);
    return {
      ...insight,
      disclaimer: "Informational only. Discuss persistent or concerning changes with a healthcare professional."
    };
  }

  async getOne(userId: string, id: string) {
    const entries = await this.loadEntries(userId, new Date(0), id);
    const entry = entries[0];
    if (!entry) {
      throw new Error("Journal entry not found");
    }
    return {
      id: entry.id,
      occurredAt: entry.occurredAt,
      rawText: this.crypto.decrypt(entry.rawTextCiphertext, entry.rawTextNonce),
      structured: entry.structuredJson,
      extraction: entry.extraction?.extractedJson,
      analysisSource: entry.extraction?.analysisSource ?? "not_analyzed",
      analysisModel: entry.extraction?.model ?? null,
      redFlags: entry.redFlags
    };
  }

  private async ensureDemoUser(userId: string) {
    const result = await this.db.query(`SELECT id FROM ${this.db.table("users")} WHERE id = $1`, [userId]);
    if (!result.rows[0]) {
      throw new Error("Authenticated user was not found.");
    }
  }

  private async loadEntries(userId: string, since: Date, id?: string) {
    const params: unknown[] = [userId, since];
    const idClause = id ? "AND je.id = $3" : "";
    if (id) params.push(id);

    const entryResult = await this.db.query<JournalEntryRow>(
      `SELECT je.id, je.occurred_at, je.raw_text_ciphertext, je.raw_text_nonce, je.structured_json
       FROM ${this.db.table("journal_entries")} je
       WHERE je.user_id = $1 AND je.occurred_at >= $2 ${idClause}
       ORDER BY je.occurred_at ASC`,
      params
    );

    const entries = [];
    for (const row of entryResult.rows) {
      const extractionResult = await this.db.query<ExtractionRow>(
        `SELECT extracted_json, analysis_source, model FROM ${this.db.table("ai_extractions")} WHERE journal_entry_id = $1`,
        [row.id]
      );
      const redFlagResult = await this.db.query<RedFlagRow>(
        `SELECT category, severity, guidance, matched_text, created_at
         FROM ${this.db.table("red_flag_events")}
         WHERE journal_entry_id = $1
         ORDER BY created_at ASC`,
        [row.id]
      );

      entries.push({
        id: row.id,
        occurredAt: row.occurred_at,
        rawTextCiphertext: row.raw_text_ciphertext,
        rawTextNonce: row.raw_text_nonce,
        structuredJson: row.structured_json,
        extraction: extractionResult.rows[0]
          ? {
              extractedJson: extractionResult.rows[0].extracted_json,
              analysisSource: extractionResult.rows[0].analysis_source,
              model: extractionResult.rows[0].model
            }
          : undefined,
        redFlags: redFlagResult.rows.map((flag) => ({
          category: flag.category,
          severity: flag.severity,
          guidance: flag.guidance,
          matchedText: flag.matched_text,
          createdAt: flag.created_at
        }))
      });
    }

    return entries;
  }
}
