

on:
  # Triggers automatically whenever you push code to main
  push:
    branches: ["main"]

  # Magic keyword that adds the permanent "Run workflow" button
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Prevent overlapping parallel deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # If your website files are inside a sub-folder (like 'docs' or 'public'), change "." to "./docs"
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
